# Generated by Django 5.2.6 on 2025-11-04 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fabricante', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_lanzamiento', models.DateField()),
                ('imagen', models.URLField(blank=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVideomaniacos.genero')),
                ('plataformas', models.ManyToManyField(to='appVideomaniacos.plataforma')),
            ],
        ),
    ]
