# Generated by Django 5.2.7 on 2025-11-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVideomaniacos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='videojuegos/'),
        ),
    ]
