# Generated by Django 5.2.7 on 2025-11-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVideomaniacos', '0002_videojuego_score_alter_videojuego_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='imagen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
